### ISSUE TITLE
Safe to remove Enterprise App once custom App Registration created?

### ISSUE THREAD

**Issue by iyerusad** [immense/immybot-documentation#31]
As far as I can tell it seems like its safe to remove the Enterprise App once the custom permissions App Registration has been created.

Can you confirm/Add to doc? Trying to avoid legacy pieces.

https://docs.immy.bot/azure-graph-permissions-setup.html#custom

**Comment by MWGMorningwood** [comment]
The default Enterprise App handles logging into Immy itself. Your custom one is just for integration/task/deployment permissions.  
I would not advise disabling it. Take a peek at the interactive sign-in logs on each.

**Comment by iyerusad** [comment]
Yup yup, that looks correct over past few months of testing, closing.
